name: emp-salary-deployment
namespace: demo-dev2

# Service Account

serviceAccount:
  annotations:
    {}

# Service 

service:
  name: emp-salary-service
  namespace: demo-dev2
  type: ClusterIP
  ports:
    protocol: TCP
    port: 8080
    targetPort: 8080
    name: ot-emp-salary

# Deployment

image: 
  url: registry.buildpiper.in/emp-salary-dev2:2-20230509T0101-latest
  imagePullPolicy: IfNotPresent

deployment:
  replicas: 1
  rollingUpdate:
    maxSurge: "100%"
    maxUnavailable: "5%"
  strategyType: RollingUpdate
  minReadySeconds: 0
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  terminationGracePeriodSeconds: 30
  imagePullSecrets: nexus-regcred
  containers:
      ports:
        containerPort: 8080
        protocol: TCP
        name: ot-emp-salary
      resources:
        limits:
          cpu: 300m
          memory: 300Mi
        requests:
          cpu: 300m
          memory: 300Mi
